#!/bin/sh

###################
# SET PROMPT COLORS
###################
ZSH_PROMPT_BG_A="065"
ZSH_PROMPT_BG_B="015"
ZSH_PROMPT_BG_C="000"
ZSH_PROMPT_FG_A="193"
ZSH_PROMPT_FG_B="007"
ZSH_PROMPT_FG_C="007"
