#!/bin/sh

###################
# SET PROMPT COLORS
###################
ZSH_PROMPT_BG_A="067"
ZSH_PROMPT_BG_B="239"
ZSH_PROMPT_BG_C="236"
ZSH_PROMPT_FG_A="236"
ZSH_PROMPT_FG_B="250"
ZSH_PROMPT_FG_C="250"
