#!/bin/sh

###################
# SET PROMPT COLORS
###################
ZSH_PROMPT_BG_A="001"
ZSH_PROMPT_BG_B="010"
ZSH_PROMPT_BG_C="011"
ZSH_PROMPT_FG_A="000"
ZSH_PROMPT_FG_B="012"
ZSH_PROMPT_FG_C="012"
