export DOTFILES_DIR=/repos/dotfiles
##################
# MISC ZSH OPTIONS
##################
# Smart URLs
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
# Opts
setopt long_list_jobs   # Jobs
setopt auto_cd
setopt multios
setopt cdablevars
setopt nolistbeep       # Don't beep on ambiguous completions
# Key Timeout
export PROMPT_EOL_MARK=""
export KEYTIMEOUT=1
zstyle ':completion:*' menu select=2

# Add a function path
fpath=($DOTFILES_DIR/zsh/functions $DOTFILES_DIR/zsh/completions $fpath)

###################
# PATH MANIPULATION
###################
# Force unique entries in PATH
typeset -Ug path
path=(/usr/local/bin $path $HOME/bin /usr/local/share/npm/bin /opt/chef/embedded/bin /usr/local/heroku/bin)

###################
# PYTHON VIRTUALENV
###################
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export VIRTUAL_ENV_DISABLE_PROMPT=1
source /usr/local/bin/virtualenvwrapper.sh

#############
# ZSH PLUGINS
#############
# Set up compinit
autoload -U compinit
compinit -d $DOTFILES_DIR/zsh/cache/zcomp-${HOST/.*/}

for plugin in $DOTFILES_DIR/zsh/plugins/*.zsh; do
    source $plugin
done

# Syntax Highlighting
source $DOTFILES_DIR/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[commandseparator]="fg=yellow"

# History Substring Search
source $DOTFILES_DIR/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
# Bind UP/DOWN to search substrings in history
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
# Change highlighting of history substring search
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="bg=yellow,fg=black,bold"

# Autoenv
source $DOTFILES_DIR/zsh/autoenv/activate.sh

#####################
# BASIC ENV VARIABLES
#####################
# Don't edit default merge commit messages
export GIT_MERGE_AUTOEDIT=no
# Set editor to gvim
export EDITOR="/usr/local/bin/vim -f"
export PAGER="less"
export LESS="-RXE"
export CLICOLOR=1
export LC_CTYPE=$LANG

# Allow use of ^S and ^Q in vim
stty -ixon -ixoff
stty stop undef
