export DOTFILES_DIR=$HOME/repos/dotfiles
export PROMPT_STYLE="async"

##################
# MISC ZSH OPTIONS
##################
# Smart URLs
autoload -U url-quote-magic
zle -N self-insert url-quote-magic
# Opts
setopt long_list_jobs   # Jobs
setopt auto_cd
setopt multios
setopt cdablevars
setopt nolistbeep       # Don't beep on ambiguous completions
# Key Timeout
export PROMPT_EOL_MARK=""
export KEYTIMEOUT=1
zstyle ':completion:*' menu select=2

# Add a function path
fpath=($DOTFILES_DIR/zsh/functions $DOTFILES_DIR/zsh/completions $fpath)

###################
# PATH MANIPULATION
###################
# Force unique entries in PATH
typeset -Ug path
path=(/usr/local/opt/python@3.8/bin /usr/local/bin $path $HOME/bin /usr/local/share/npm/bin)

#####################
# BASIC ENV VARIABLES
#####################
# Don't edit default merge commit messages
export GIT_MERGE_AUTOEDIT=no
# Set editor to gvim
export EDITOR="/usr/local/bin/vim"
export PAGER="less"
export LESS="-RXE"
export CLICOLOR=1
export LC_CTYPE=$LANG

# Allow use of ^S and ^Q in vim
stty -ixon -ixoff
stty stop undef

###################
# PYTHON VIRTUALENV
###################
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=python3
export VIRTUAL_ENV_DISABLE_PROMPT=1
source /usr/local/bin/virtualenvwrapper.sh

#############
# ZSH PLUGINS
#############
# Local zshrc
[[ -s $HOME/.zshrc.local ]] && source "$HOME/.zshrc.local"

# Set up brew autocompletion
if type brew &>/dev/null; then
    fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
fi

# Set up compinit
autoload -U compinit
compinit -d $DOTFILES_DIR/zsh/cache/zcomp-${HOST/.*/}

for plugin in $DOTFILES_DIR/zsh/plugins/*.zsh; do
    source $plugin
done

# Syntax Highlighting
source $DOTFILES_DIR/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=blue,bold"
ZSH_HIGHLIGHT_STYLES[commandseparator]="fg=yellow"

# History Substring Search
source $DOTFILES_DIR/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
# Bind UP/DOWN to search substrings in history
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
# Change highlighting of history substring search
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="bg=yellow,fg=black,bold"

# Auto-Suggestions
source $DOTFILES_DIR/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# fzf
export FZF_DEFAULT_COMMAND="rg --files --no-ignore --hidden --follow --glob '!.git/*' --glob '!__pycache__/*' --glob '!node_modules/*' --glob '!*.pyc'"
[[ -s ~/.fzf.zsh ]] && source ~/.fzf.zsh

# direnv
eval "$(direnv hook zsh)"

# RVM
path=($path $HOME/.rvm/bin)
fpath=($HOME/.rvm/scripts/zsh/Completion $fpath)
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
# eval "$(rbenv init -)"

# Thefuck
which thefuck > /dev/null && eval $(thefuck --alias)

# Go
path=($path /usr/local/go/bin)

# Ripgrep
export RIPGREP_CONFIG_PATH=$DOTFILES_DIR/misc/rgconfig

##########################
# PLATFORM SPECIFIC CONFIG
##########################
# Ubuntu
[[ -s /etc/zsh_command_not_found ]] && source /etc/zsh_command_not_found
