export DOTFILES_DIR=/repos/dotfiles
#############
# ZSH OPTIONS
#############
setopt HIST_IGNORE_ALL_DUPS

###################
# PATH MANIPULATION
###################
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:/Users/ryan/bin
# NPM binaries
export PATH=$PATH:/usr/local/share/npm/bin

###################
# PYTHON VIRTUALENV
###################
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python
export VIRTUAL_ENV_DISABLE_PROMPT=1
source /usr/local/bin/virtualenvwrapper.sh

#######################
#
# Oh-My-Zsh via Antigen
#
#######################
export ENABLE_CORRECTION="true"
export PROMPT_EOL_MARK=""
source $HOME/.antigen/antigen.zsh

# Use Oh-My-Zsh's /lib/
antigen use oh-my-zsh

# Oh-My-Zsh plugins
antigen bundle autoenv
antigen bundle brew
antigen bundle celery
antigen bundle colored-man
antigen bundle fabric
antigen bundle git
antigen bundle jsontools
antigen bundle node
antigen bundle npm
antigen bundle osx
antigen bundle pip
antigen bundle python
antigen bundle redis-cli
antigen bundle urltools
antigen bundle web-search
antigen bundle zsh_reload
# Command line syntax highlighting!
antigen bundle zsh-users/zsh-syntax-highlighting
# History sub-string search
antigen bundle zsh-users/zsh-history-substring-search
# Auto environments!
antigen bundle kennethreitz/autoenv

# My custom scripts
antigen bundle $DOTFILES_DIR/zsh/plugins/django
antigen bundle $DOTFILES_DIR/zsh/custom

antigen apply

# Bind UP/DOWN to search substrings in history
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
# Change highlighting of history substring search
export HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND="bg=yellow,fg=black,bold"

zstyle ':completion:*' menu select=2

# Store completion cache files in $DOTFILES_DIR/zsh/completion_cache
export ZSH_PIP_CACHE_FILE=$DOTFILES_DIR/zsh/completion_cache/pip
export ZSH_DJANGO_CACHE_FILE=$DOTFILES_DIR/zsh/completion_cache/django

ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# Suspend and restart vim
foreground-vim() {
    fg %vim
}
zle -N foreground-vim
bindkey "^Z" foreground-vim

#####################
# BASIC ENV VARIABLES
#####################
# Don't edit default merge commit messages
export GIT_MERGE_AUTOEDIT=no
# Set editor to gvim
export EDITOR="/usr/local/bin/vim -gf"
export CLICOLOR=1

# Aliases
tn() {
    local message="Process has finished"
    if [[ $1 == "-message" ]]; then
        message=$2
        shift; shift;
    fi
    local prog=$1
    shift
    $prog $@
    /Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier -message "$message" -subtitle "$prog" > /dev/null
}
alias nw="/Applications/node-webkit.app/Contents/MacOS/node-webkit"
alias tree="tree -I '*.pyc|*.un~|*.sw[op]|*node_modules*|%*|.DS_Store|.git' -Ca"
alias pman="man-preview"

alias git="hub"
alias gcd="git checkout develop"
alias gss="git status -sb"
alias glg="git --no-pager log -n 25 --format=format:'%C(reset)%C(yellow)%h - %C(red)%ar%C(reset) %C(green)<%an> %C(reset)%s%C(bold yellow)%d'"
alias glgg="git log --format=format:'%C(reset)%C(yellow)%h - %C(red)%ar%C(reset) %C(green)<%an> %C(reset)%s%C(bold yellow)%d'"
alias gstl="git --no-pager stash list"
alias gpr="git pull-request -o -b ycharts:develop -h ryankuczka:$(current_branch)"

# Ruby binaries
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
export PATH=$PATH:/usr/local/opt/ruby/bin

rvm use 1.9.3 > /dev/null

###########
# Heroku
###########
export PATH="$PATH:/usr/local/heroku/bin"
